language: node_js
node_js: '12'
dist: xenial
services:
  - docker
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - sudo bash -c "curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.6.1/hyperdrive > /usr/local/bin/hyperdrive"
  - sudo chmod +x /usr/local/bin/hyperdrive
  - hyperdrive -y --name "Landobot" --email landobot@lando.dev
  - lando version
script:
  - lando start
  - lando lint
  - lando test
